:sparkles: Add footer, body-width reduced
dotkom/vengeful-vineyard pull request #46
Opened 2020-11-15 17:41 UTC by annaiandresen

2020-11-15 21:24 UTC, jfremstad requested changes

2020-11-15 22:58 UTC, annaiandresen commented on frontend/src/Components/Footer/Footer.svelte
> +<div class="footer">
Sånn!

2020-11-16 15:55 UTC, jfremstad approved these changes

2020-11-16 15:56 UTC, jfremstad commented
Nice!

2020-11-16 15:56 UTC, merged